Cosmetics: Consistent spelling of "tmux"

diff --git a/bin/tmux-activate-pane b/bin/tmux-activate-pane
--- a/bin/tmux-activate-pane
+++ b/bin/tmux-activate-pane
@@ -26,7 +26,7 @@ case "$1" in
 esac
 
 if [ ! "$TMUX" ]; then
-    echo >&2 'Not in a TMUX session!'
+    echo >&2 'ERROR: Not in a tmux session.'
     exit 1
 fi
 
